#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

hsetroot -solid "#83A8A6"

# nitrogen --set-scaled /home/varshith/wallpaper.jpg

# Set decoration geometry
berryc inner_border_width 0
berryc title_height       30
berryc border_width       0
berryc top_gap            30
berryc inner_focus_color F25F5C
berryc inner_unfocus_color C44536

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Iosevka"

picom --experimental-backend
