#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 0

# nitrogen --set-scaled /home/varshith/wallpaper.png
hsetroot -solid "#83A8A6"

picom -b
